name: Poten HooHae

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.POTEN_HOST }}
          username: ${{ secrets.POTEN_USERNAME }}
#          key: ${{ secrets.POTEN_PRIVATE_KEY }}
          password: ${{ secrets.POTEN_PASSWORD }}
          port: ${{ secrets.POTEN_SSH_PORT }}
          script_stop: true
          script: | 
            cd /home/hoohae/Hoo-Hae/
            git pull origin master
            cd back  
            ./gradlew clean build -x test
            sudo fuser -k -n tcp ${{ secrets.POTEN_BACK_PORT }} || true
            nohup java -jar /home/hoohae/Hoo-Hae/back/build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &