name: Poten HooHae

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: Ubuntu 22.04.4 LTS
    steps:
      - name: SSH 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.POTEN_HOST }}
          username: ${{ secrets.POTEN_USERNAME }}
          password: ${{ secrets.POTEN_PASSWORD }}
          port: ${{ secrets.POTEN_SSH_PORT }}
          script_stop: true
          script: |
            cd ${{ secrets.POTEN_DIR_NAME }}/Hoo-Hae/back
            git pull origin master
            ./gradlew clean build -x test
            sudo fuser -k -n tcp ${{ secrets.POTEN_BACK_PORT }} || true
            sh ${{ secrets.POTEN_DIR_NAME }}/Hoo-Hae/back/scripts/build_spring.sh
