name: Poten HooHae

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.POTEN_HOST }}
          username: ${{ secrets.POTEN_USERNAME }}
#          key: ${{ secrets.POTEN_PRIVATE_KEY }}
          password: ${{ secrets.POTEN_PASSWORD }}
          port: ${{ secrets.POTEN_SSH_PORT }}
          script_stop: true
          script: |
            export JAVA_HOME=/home/hoohae/jdk-17
            export PATH=$JAVA_HOME/bin:$PATH
            cd /home/hoohae/Hoo-Hae/
            git pull origin master
            /home/hoohae/Hoo-Hae/back/gradlew clean build -x test --info
            sudo fuser -k -n tcp ${{ secrets.POTEN_BACK_PORT }} || true
            sh /home/hoohae/Hoo-Hae/back/scripts/build_spring.sh